### ISSUE TITLE
`sc.mergedicts` fails with non-dicts by default

### ISSUE THREAD

**Issue by RomeshA** [sciris/sciris#366]
Sciris 1.3.3

```
In[3]: sc.mergedicts({'a':1,'b':2},False)
Out[3]: {'a': 1, 'b': 2}
```
Current version

```
In[3]: sc.mergedicts({'a':1,'b':2},False)
Traceback (most recent call last):
  File "C:\Users\romesh\miniconda3\envs\atomica38\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-d5df2e0e3789>", line 1, in <module>
    sc.mergedicts({'a':1,'b':2},False)
  File "C:\Users\romesh\projects\sciris\sciris\sc_utils.py", line 1111, in mergedicts
    raise TypeError(errormsg)
TypeError: Could not handle argument 1 of <class 'bool'>: expecting dict or None
```

There are some parts of Covasim that rely on the v1.3.3 behaviour (this issue is causing some failures in Covasim's test suite)

**Comment by cliffckerr** [comment]
@RomeshA I think this is a bug in Covasim, rather than Sciris -- I don't think it's intuitive that `sc.mergedicts({'a':1,'b':2},False)` _should_ give `{'a': 1, 'b': 2}`. Covasim is supposed to allow `show_args` to be a boolean to disable all optional plotting, but actually it was silently ignored in Sciris v1.3.3. So it's a slight improvement that it now raises an error, but the next step is to fix it in Covasim :)

**Comment by RomeshA** [comment]
Makes sense, looks like it is straightforward to fix in Covasim. The docstring for `mergedicts` still describes the original behaviour ('By default, skips things that are not, dicts (e.g., None)')  so that should probably be updated

**Comment by cliffckerr** [comment]
Closing here in favor of the bug in Covasim: https://github.com/amath-idm/covasim/issues/1391
